# Site settings
title: Maxime Capuano Portfolio
description: Maxime Capuano's portfolio
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://malkaviel.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Maxime Capuano
user_description: I am a french Web and 3D software programmer.
  My studies and personal projects are centered around the development of game engines and 3D graphics software.
  My professional experience is about the development of website backends and internal web tools.
user_title: Web and 3D software developer
email: maxime.capuano@tutanota.com
twitter_username:
github_username: Malkaviel
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
