# Site settings
title: Maxime Capuano Portfolio
description: Maxime Capuano's portfolio
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://malkaviel.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Maxime Capuano
user_description: I am a french fullstack web developer.
  Most of my experience lies in the back-end side of web development, be it in PHP, C# or Java, with some experience with the Angular
  framework for the front-end side.
user_title: Web developer
email: maxime.capuano@tutanota.com
twitter_username:
github_username: Malkaviel
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
